name: Simple Deploy

on:
    push:
        branches: [main, master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy notification
              run: |
                  echo "🚀 Deploying to RunPod..."
                  echo "Branch: ${{ github.ref_name }}"
                  echo "Commit: ${{ github.sha }}"
                  echo "Author: ${{ github.actor }}"
                  echo ""
                  echo "✅ RunPod will automatically detect this push and deploy the changes"
                  echo "📍 Check your RunPod console for build status"

            - name: Create deployment status
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.repos.createDeployment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        ref: context.sha,
                        environment: 'runpod',
                        description: 'Auto deploy to RunPod',
                        auto_merge: false,
                        required_contexts: []
                      })
